# Generated by Django 3.2.14 on 2022-08-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Team',
        ),
    ]
